exhaust_test: false


# ModelParams
scene_type: "KittiMot"
start_frame: 380
end_frame: 431
num_pts: 1000000
cam_num: 1
resolution_scales: [1]
eval: false
t_init: 0.006
fix_radius: 0.0
including_dynamic: true
adding: false
# PipelineParams
nuscenes: false
# OptimizationParams
iterations: 40000
densify_until_iter: 20000
densify_until_num_points: 3000000
dynamic_densify_until_iter: 20000
opacity_lr: 0.007

densification_interval: 200
sh_increase_interval: 2000
opacity_reset_interval: 5000
densify_grad_threshold: 0.00015
size_threshold: 100
big_point_threshold: 0.4

lidar_decay: 0.3
lambda_v_reg: 0.01
