exhaust_test: false


# ModelParams
scene_type: "Waymo"
resolution_scales: [1]
fisheye_cam_num: 2
cam_num: 4
long_cam_num: 1
is_fisheye: False
long_focus: True
initialization: False
eval: false
target_path: ???
num_pts: 600000

t_init: 0.1
separate_scaling_t: 0.2
enlarge: False
save_point_cloud: False
dynamic_removal: False
pos_shift: [0, 0, 0]
pos_rotation: [0, 0, 0.0]
select_obj_id: [70]
removal_thresh: 0.999999
# PipelineParams
require_boundingbox: False
including_dynamic: true
is_training: False
adding: false
nuscenes: False
# OptimizationParams
iterations: 30000
opacity_lr: 0.005

densify_until_iter: 15000
densify_grad_threshold: 0.00017
sh_increase_interval: 2000
fix_radius: 10.0


lambda_v_reg: 0.01


