exhaust_test: false


# ModelParams
scene_type: "Waymo"
resolution_scales: [4]
fisheye_cam_num: 2
cam_num: 4
long_cam_num: 1
is_fisheye: False
long_focus: True
initialization: false
eval: false
num_pts: 600000
t_init: 0.1
separate_scaling_t: 0.2
pos_shift: false #[5]
pos_rotation: false #[5]
reg3d_interval: 10
reg3d_k: 5
reg3d_lambda_val: 2
reg3d_max_points: 100000
reg3d_sample_size: 1000
lambda_dssim: 0.2
# PipelineParams
is_training: True
require_boundingbox: False
nuscenes: False
# OptimizationParams
iterations: 30000
including_dynamic: False
opacity_lr: 0.005
adding: False

densify_until_iter: 15000
dynamic_densify_until_iter: 15000
densify_grad_threshold: 0.00017
sh_increase_interval: 2000
fix_radius: 0.0


lambda_v_reg: 0.01


